name: Continuous Delivery

on:
  push:
    branches:
      - master
      - release/*

jobs:
  delivery:
    name: Node 14.x
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0

      - name: Set global git user and email
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Set up Node.js version 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
          scope: trutoo

      - name: Append npm registry authentication to .npmrc
        run: |
          echo -e '\n//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}\n' >> ${NPM_CONFIG_USERCONFIG}

      - name: Install dependencies using CI
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Used in .npmrc to install packages from github

      - name: Run tests on package
        run: npm test

      - name: Update coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish package to GitHub Packages and GitHub Release
        run: npm run release
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Used to verify access through semantic release
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Used by standard npm publish
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Used for github releases through semantic release

      - name: Publish package to NPM
        run: npm publish --access public --@trutoo:registry=https://registry.npmjs.org
        if: env.VERSION != null # Only if semantic-release publishes the package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Used by standard npm publish
