name: Continuous Delivery

on:
  push:
    branches:
      - main
      - release/*

jobs:
  delivery:
    name: Node 20.x
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set global git user and email
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: ⚙️ Enable corepack
        if: inputs.enable-corepack == 'true'
        shell: bash
        working-directory: ${{ inputs.cwd }}
        run: corepack enable

      - name: Set up Node.js version 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: 📥 Install dependencies
        uses: ./.github/actions/install

      - name: Run tests on package
        run: yarn test

      - name: Update coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish package to GitHub Packages and GitHub Release
        run: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }} # Used to verify access through semantic release
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }} # Used by standard npm publish
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Used for github releases through semantic release
